### ISSUE TITLE
MailGun response body: [Connection Failure] Error Code	500

### ISSUE THREAD

**Issue by ivanionut** [DominicWatson/cfmailgun#64]
hi,
for several days I get the following error:

> An unexpted response was returned from the MailGun server. MailGun response body: [Connection Failure]
Error Code	500

Is it my mistake or has something changed in the API?

**Comment by DominicWatson** [comment]
Not afaik. Suffering from SSL certificate problems perhaps? The error is clearly a connection failure between your application and the Mailgun endpoint. Run a search for mailgun + lucee SSL certificate issues, that might be it.
